### ISSUE TITLE
Will DgraphProto.SchemaNode come back again?

### ISSUE THREAD

**Issue by Valdanitooooo** [dgraph-io/dgraph4j#106]
I'm trying to use the latest version

**Comment by mangalaman93** [comment]
We have removed the `SchemaNode` struct (protobuff messsage) from `api.proto` file in v2. It is still available in v1. I am wondering what use case you have that uses `SchemaNode`.

**Comment by Valdanitooooo** [comment]
Used only for querying schema lists. Close this, please.
