### ISSUE TITLE
Sample production configuration for Java grpc client

### ISSUE THREAD

**Issue by ajaydivakaran** [dgraph-io/dgraph4j#111]
The below link talks about a single connection.
https://github.com/dgraph-io/dgraph4j#creating-a-client

Could you please elaborate what a typical production configuration would look like?
How do I create more than 1 connection, pool configuration?

**Comment by ajaydivakaran** [comment]
I see the deadline set via an interceptor later in the documentation.

**Comment by mangalaman93** [comment]
You can create as many stubs as there are Alpha nodes running -
``` 
ManagedChannel channel1 = ManagedChannelBuilder
    .forAddress("localhost", 9080)
    .usePlaintext().build();
DgraphStub stub1 = DgraphGrpc.newStub(channel1);

ManagedChannel channel2 = ManagedChannelBuilder
    .forAddress("localhost", 9082)
    .usePlaintext().build();
DgraphStub stub2 = DgraphGrpc.newStub(channel2);

ManagedChannel channel3 = ManagedChannelBuilder
    .forAddress("localhost", 9083)
    .usePlaintext().build();
DgraphStub stub3 = DgraphGrpc.newStub(channel3);

DgraphClient dgraphClient = new DgraphClient(stub1, stub2, stub3);
```

**Comment by mangalaman93** [comment]
I also raised a PR to update README https://github.com/dgraph-io/dgraph4j/pull/114

**Comment by ajaydivakaran** [comment]
In your example mentioned above is 3 instances of Alpha running?

**Comment by mangalaman93** [comment]
Correct, and all of them running locally (localhost). You will have to use the correct IP for each instance.

**Comment by ajaydivakaran** [comment]
How about for a single Alpha instance. Is there a way to have multiple connections to it?

**Comment by mangalaman93** [comment]
For that, you can potentially pass multiple stubs to same Alpha node, though, I think that's not really very useful.

**Comment by ajaydivakaran** [comment]
ok. Thanks @mangalaman93 for your suggestions.
