### ISSUE TITLE
TestCase AcctUpsertTest and DgraphAsyncClientTest Failed

### ISSUE THREAD

**Issue by darionyaphet** [dgraph-io/dgraph4j#113]
```
io.dgraph.AcctUpsertTest.beforeClass FAILED
    java.lang.AssertionError

io.dgraph.DgraphAsyncClientTest.beforeClass FAILED
    java.util.concurrent.CompletionException
        Caused by: io.grpc.StatusRuntimeException
            Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException
                Caused by: java.net.ConnectException
```

**Comment by mangalaman93** [comment]
Seems like that tests are unable to connect to Alpha. Could you let us know how you are running the tests?

**Comment by darionyaphet** [comment]
`./gradlew test` thanks

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/7760). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
