### ISSUE TITLE
client should support close method 

### ISSUE THREAD

**Issue by Willem520** [dgraph-io/dgraph4j#122]
now,the close method is not convenient
![image](https://user-images.githubusercontent.com/26085817/71875366-15771000-315f-11ea-8dd2-fd589047a3c0.png)
it means we should save channel by myself,maybe we should provide client close methd like
`public void close(){
        channels.stream().forEach(item -> {
            item.shutdown();
        });
    }`
or more easy to use

**Comment by mangalaman93** [comment]
If we do this, we could add at least following 3 functions-
* open
* openWithTLS
* close

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/0). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
