### ISSUE TITLE
Add example of creating client with TLS

### ISSUE THREAD

**Issue by hubie** [dgraph-io/dgraph4j#123]
I'm having difficulty in successfully configuring the client to connect to Dgraph using TLS.

Could you provide/document an example of how this would be set up?

Thanks!

**Comment by sleto-it** [comment]
Hi @hubie,

Sorry if this took some time. We just merged a PR which includes an example. Please take a look at the following section and let us know if this helps you or if you have additional questions:

- https://github.com/dgraph-io/dgraph4j#creating-a-secure-client-using-tls

Thanks again for opening this ticket,
