### ISSUE TITLE
Throrough testing

### ISSUE THREAD

**Issue by deepakjois** [dgraph-io/dgraph4j#14]
* Port over integration tests in: https://github.com/dgraph-io/dgraph/tree/master/contrib/integration
* Table-driven testing: It would be nice to have a set of query/response pairs, where the query can be read from a file and run against a server, and then compared against the expected response output.

**Comment by deepakjois** [comment]
I have ported over 3 integration tests from Go in 98e9f56bb65a2d95da70bcbda62252e9d53680ff

It seems sufficient for now. I will close this issue, and move on to other minor fixes and Travis integration.

**Comment by manishrjain** [comment]
Nice work!
