### ISSUE TITLE
Supporting gRPC with TLS on Java 8

### ISSUE THREAD

**Issue by danielmai** [dgraph-io/dgraph4j#144]
By default, TLS over gRPC is only supported on Java 9 and later. Java 9 is no longer supported.

According to [grpc-java](https://github.com/grpc/grpc-java/blob/master/SECURITY.md#tls-on-non-android), we can include grpc-netty-shaded as part of dgraph4j so that the necessary SSL libraries are available for Java 8 for Windows, macOS, and Linux:

> JDK versions prior to Java 9 do not support ALPN and are either missing AES GCM support or have 2% the performance of OpenSSL.
>
> We recommend most users use grpc-netty-shaded, which includes netty-tcnative on BoringSSL. It includes pre-built libraries for 64 bit Windows, OS X, and 64 bit Linux. For 32 bit Windows, Conscrypt is an option. For all other platforms, Java 9+ is required.

Java 8 and Java 11 are the current Java LTS releases, so it makes sense to support Java 8 for users that are still on that version.

What do you think, @abhimanyusinghgaur?

**Comment by abhimanyusinghgaur** [comment]
Yes, I agree. I will test this on my system and see if it works.
