### ISSUE TITLE
Connection health check when creating client

### ISSUE THREAD

**Issue by damienburke** [dgraph-io/dgraph4j#145]
Hi, I was wondering if there was a way to check if a connection to a Dgraph instance is available immediately after the dgraph4j client is setup. This way, I can check before hand if my first queries/mutations are going to fail.

https://github.com/dgraph-io/pydgraph/issues/128 reported identical request and was "fixed" by exposing check_version call.
Thanks

**Comment by abhimanyusinghgaur** [comment]
Thanks @damienburke,

We will look into it.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/7770). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
