### ISSUE TITLE
Uid problem

### ISSUE THREAD

**Issue by zhaojiangkun** [dgraph-io/dgraph4j#188]
The following exception occurred when I manually set the uid value:
**io.grpc.StatusRuntimeException: UNKNOWN: Uid: [726896] cannot be greater than lease: [600000]**

Are there any restrictions on uid？

**Comment by mangalaman93** [comment]
yes, UIDs need to be allocated from Zero before it could bs used. I see there is a graphQL API that one could use as explained here https://dgraph.io/docs/graphql/admin/#admin (look for AssignedIds)

**Comment by MichelDiz** [comment]
You are probably entering data from another Dgraph cluster. Reimportant perhaps. Ideally, you should not reuse UIDs. Always use Blank Nodes.

e.g

```RDF
 _:New <user.name> "Bob" .
 ```
 Or
 ```JSON
{ "uid": "_:New", "user.name": "Bob" } 
 ```
