### ISSUE TITLE
Generate proto Java classes with @Generated annotation

### ISSUE THREAD

**Issue by liqweed** [dgraph-io/dgraph4j#20]
Adding the `@javax.annotation.Generated` annotation to the generated Java classes allows FindBugs, errorprone and other code inspection tools to ignore these files.

**Comment by deepakjois** [comment]
It looks like all the code for the grpc classes is already annotated like:

```Java
@javax.annotation.Generated(
    value = "by gRPC proto compiler (version 1.7.0)",
    comments = "Source: task.proto")
```

However, `DgraphProto` doesn’t have this annotation. There is an open issue about it here: https://github.com/google/protobuf/issues/42

I don’t think we can do much about it till they fix it upstream. Leaving it open for now, hoping this will happen soon enough.
