### ISSUE TITLE
Ready for 1.0

### ISSUE THREAD

**Issue by Solido** [dgraph-io/dgraph4j#3]
The API is moving fast and Java driver was put aside but still many server side app rely on it. Any plan on the roadmap for a compatible and up to date driver ?
It's important for the adoption of dgraph since Json is not a good options with large volume.
Thanks.

**Comment by deepakjois** [comment]
We have started work on a Java client that would be officially supported. I just pushed some changes in 5b458ec706771ae6128239bce864c3941ce4482c to support the latest grpc interface. There is still a few more things to be done before it is ready for general use.

I am going to close this issue and create separate issues to track the progress.
