### ISSUE TITLE
now,how do i insert edge'data?

### ISSUE THREAD

**Issue by lxwithgod** [dgraph-io/dgraph4j#32]
v0.9.2
dgraphclient.newTransaction().query,this function can't insert/delete data,
please tell  me,how do i insert edge'data?

**Comment by raitraidma** [comment]
Insert using JSON:
```
DgraphClient.Transaction transaction = getDgraphClient().newTransaction();
DgraphProto.Mutation mutation = DgraphProto.Mutation.newBuilder()
    .setSetJson(ByteString.copyFromUtf8("[" +
        "{\"uid\":\"0x123\", \"name\":\"Tom\"}," +
        "{\"name\":\"Jane\"}]"))
    .build();
transaction.mutate(mutation);
transaction.commit();
```

However, I'm also curious how to insert data using `DgraphProto.NQuad` and how to use [blank nodes](https://docs.dgraph.io/query-language/#blank-nodes-and-uid) with dgraph4j.

**Comment by lxwithgod** [comment]
can you insert edge relationship?
DgraphClient.Transaction transaction = getDgraphClient().newTransaction();
DgraphProto.Mutation mutation = DgraphProto.Mutation.newBuilder()
    .setSetJson(ByteString.copyFromUtf8(
        "{\"uid\":\"0x123\", \"call\":\"0x124\"}"))
    .build();
transaction.mutate(mutation);
transaction.commit();

**Comment by lxwithgod** [comment]
i meet a except:
io.dgraph.DgraphException: Input for predicate call of type uid is scalar

**Comment by raitraidma** [comment]
They have added new tests that are helpful: https://github.com/dgraph-io/dgraph4j/blob/master/src/test/java/io/dgraph

**Comment by deepakjois** [comment]
We have added some code in the tests folder which should illustrate the different scenarios. Hopefully they can guide you along in writing your own code to perform insertions.
