### ISSUE TITLE
Client v0.9.2 does not work with Server v0.9.3

### ISSUE THREAD

**Issue by raitraidma** [dgraph-io/dgraph4j#38]
When running Dgraph v0.9.3 and trying to mutate database using Dgraph4j v0.9.2 then it throws an exception:
`io.grpc.StatusRuntimeException: UNIMPLEMENTED: unknown service protos.Dgraph`

~~Might be connected to improvement in [new server version](https://github.com/dgraph-io/dgraph/releases/tag/v0.9.3):
Proto definitions are split into intern and api. Users using v0.9.x of the Go client will have to change their code to use api instead of proto as package name.~~

Compared api.proto files and client's proto file is missing
`bool ignore_index_conflict = 15;` in `message Mutation`, so probably is this the issue.

**Comment by deepakjois** [comment]
I will make a new release of dgraph4j soon, which will work with the latest version of dgraph. Till then, you could use the master branch.

**Comment by deepakjois** [comment]
dgraph4j 0.9.3 has been released on Maven. It should work with dgraph server v0.9.4 (the latest that was released yesterday).
