### ISSUE TITLE
Make Transaction impement AutoCloseable

### ISSUE THREAD

**Issue by nkiesel** [dgraph-io/dgraph4j#42]
This would allow for a much more fluent:
```java
try (Transaction txn = dgraphClient.newTransaction()) {
   ...
   txn.commit();
}
```

**Comment by deepakjois** [comment]
I did not know about `AutoCloseable`: https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html

It is probably worth doing.
