### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by pcpshephertz** [dgraph-io/dgraph4j#45]
Documentation at `https://github.com/dgraph-io/dgraph4j#run-a-query` contains error.
 Instead of ` Response res = dgraphClient.newTransaction().query(query, vars);` 

it should be 

`Response res = dgraphClient.newTransaction().queryWithVars(query, vars);`. 

I will be happy to request a pull and commit if you verify my finding is correct.

**Comment by peterstace** [comment]
@pcpshephertz , you're correct. Please raise a PR :)

**Comment by deepakjois** [comment]
I believe it is fixed now.

**Comment by pcpshephertz** [comment]
Yes, its fixed
