### ISSUE TITLE
Update grpc-java version to 1.10.0

### ISSUE THREAD

**Issue by liqweed** [dgraph-io/dgraph4j#51]
The current version of grpc-java dependency version is 1.7.0 there have been many improvements since:
https://github.com/grpc/grpc-java/releases

We're using gRPC in our endpoints as well as the dgraph client and get grpc-java as a transitive dependency. We'd like to take advantage of the newer version.

**Comment by deepakjois** [comment]
I will create a pull request for this, and make sure the CI does not complain. After that, it should be trivial to merge it

**Comment by deepakjois** [comment]
The build passes, so this should be a safe upgrade. I will create a PR from the web interface, but I no longer have a working setup for this, so somebody else will have to pull this in.
