### ISSUE TITLE
Kotlin Muti Platform Support

### ISSUE THREAD

**Issue by joelhandwell** [dgraph-io/dgraph4j#61]
Is kotlin considered for the client library language? Especially, [multi-platform library](https://kotlinlang.org/docs/reference/multiplatform.html) using Kotlin/JS and Kotlin/Native will enable shared code among jvm, js, android and ios. As there are already jvm and js client, Kotlin support can start with creating common code with jvm and js implementation behind. How does this sound?

**Comment by deepakjois** [comment]
We had a brief chat about this. We do not have the resources or the know-how to commit to an official Kotlin client at the moment.

If someone from the Dgraph community builds a Kotlin client, we could accept a pull request into dgraph4j for any kind of kotlin interop.

**Comment by deepakjois** [comment]
We will gladly accept a PR that would identify any potential issues w/ Kotlin interop and fix them.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/7738). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
