### ISSUE TITLE
I wonder if method Assigned.getContext().getAborted() really works

### ISSUE THREAD

**Issue by iivum** [dgraph-io/dgraph4j#83]
Hi,
    When my transaction was aborted ,there was always throws an `StatusRuntimeException` and my code block  of  checking `Assigned.getContext().getAborted()` never reached. Any Information about this? thanks.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/7748). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
