### ISSUE TITLE
shade grpc dependency

### ISSUE THREAD

**Issue by mangalaman93** [dgraph-io/dgraph4j#84]
If we shade the grpc dependency of Java client, it would avoid conflicts with a different version of grpc dependency that user code might have. I have faced these issues with Spark (or MapR), spark internally uses its own grpc version that will, for sure, conflict with java client. Shading, will solve this problem permanently. We will have to figure out a way to serve the shaded jar as production jar, though.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/7749). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
