### ISSUE TITLE
queryWithVars -- how to specify multiple uids?

### ISSUE THREAD

**Issue by wiradikusuma** [dgraph-io/dgraph4j#97]
Given this signature:

    public Response queryWithVars(final String query, final Map<String, String> vars)

How do I pass multiple value (uids) with the same key?

**Comment by campoy** [comment]
Hey @gitlw, I think you're probably the best person to answer this question.

**Comment by wiradikusuma** [comment]
Tried passing string "0xAAA,0XBBB" (comma-separated text) -- doesn't work :D

**Comment by campoy** [comment]
Hey @mangalaman93, please have a look at this issue.

**Comment by mangalaman93** [comment]
Related to https://github.com/dgraph-io/dgraph/issues/2726

**Comment by MichelDiz** [comment]
BTW guys, a workaround for this would be something like
```
query q($name1:string = "Ridley Scott", $name2:string = "Steven Spielberg") {
  me(func: eq(name@en, [$name1, $name2])) {
    name@en
    director.film @filter(lt(initial_release_date, "1980-01-01"))  {
      initial_release_date
      name@en
    }
  }
}
```

You pass each value separately into variables. Hence use them as above.

Details of this support https://github.com/dgraph-io/dgraph/pull/2981
